### ISSUE TITLE
Lottie not stable with Expo - Not auto playing, getting stuck - v5.0.1

### ISSUE THREAD

**Issue by jacksonHendric** [lottie-react-native/lottie-react-native#925] opened 2022-08-19 14:56 UTC
### Description

Lottie getting stuck or not playing at all. Sometimes works with no issues but unstable for no reason.

### Steps to Reproduce

1. Use this package with Expo v44.0.0
2. Expo forces lottie package version to be v5.0.1 do to compatibility issues.
3. Use any example of usage on iOS (haven't tested on Android simulator)

**Expected behavior:**
If auto play is enabled for the lottie to start on mount

**Actual behavior:** 
With some lottie json auto play works, sometimes with the same file it doesn't. 
Some times only the first frame is shown, but doesn't play

### Versions
 `lottie package v5.0.1 (forced by expo)`.

**Comment by jacksonHendric** [comment] 2022-08-19 14:57
Why does expo force v5.0.1 and not the latest version? Did 5.0.1 have a history of issues like this? 
Example code:
`<LottieView
            style={{ width: '75%', backgroundColor: 'transparent' }}
            source={require('@assets/lottie/emailVerified.json')}
            autoPlay
            loop={false}
            onAnimationFinish={() => handleFinish()}
            speed={0.6}
          />`

**Comment by jacksonHendric** [comment] 2022-08-19 15:05
I see this issue was brought up a long time ago but this is still an issue without a solution.
[(https://github.com/lottie-react-native/lottie-react-native/issues/832)]

**Comment by delboy1978uk** [comment] 2022-08-21 11:25
Yes, you should probably close this issue then. :-)
In the meantime, I just managed to get it working there using this code: 
https://github.com/lottie-react-native/lottie-react-native/issues/832#issuecomment-1221526149

**Comment by jacksonHendric** [comment] 2022-08-21 13:56
I have already tried this and it’s not stable sometimes. Also this is not
an actual solution it’s very hacky.
Appreciate your help though.

**Comment by delboy1978uk** [comment] 2022-08-22 08:08
It's just some temp code until it gets fixed, i know its horrible and hacky :P

**Comment by fadi-quader-mox** [comment] 2022-08-26 04:53
i can reproduce it on RN 0.68.2 with React Native CLI Project

**Comment by matinzd** [comment] 2022-09-05 09:55
Is this just happening on expo? Because I could not reproduce it on bare react native project.

**Comment by fadi-quader-mox** [comment] 2022-09-07 05:52
@matinzd for me, it's reproducable on a bare react native project

**Comment by jacksonHendric** [comment] 2022-09-21 18:23
@matinzd Happening on expo 45 for me. Haven't tested on bare react native.

    "lottie-ios": "^3.4.2",
    "lottie-react-native": "5.0.1",

**Comment by delboy1978uk** [comment] 2022-11-21 10:32
I fixed it for now by creating my own Animation component. That way, each animation has it's own ref and I've not had any problems since. Here it is, if it helps anyone:

```
import React, {useEffect, useRef} from 'react';
import AnimatedLottieView from "lottie-react-native";

function Animation({source, style, onAnimationFinish, autoplay = true, loop = true, speed = 1.5}) {
    // temp ios fix begin
    // @see https://github.com/lottie-react-native/lottie-react-native/issues/832
    const lottieRef = useRef(null);
    useEffect(() => {
        lottieRef.current?.reset();
        setTimeout(() => {
            lottieRef.current?.play();
        }, 0)

    }, []);
    // fix end

    return(
        <AnimatedLottieView
            source={source}
            autoPlay={autoplay}
            loop={loop}
            style={style}
            speed={speed}
            onAnimationFinish={onAnimationFinish}
            ref={lottieRef}
        />
    );
}

export default Animation;

```

**Comment by fadi-quader-mox** [comment] 2023-02-01 02:58
I confirm this issue exists in iOS 15. I've tested it on iOS 16 and issue is fixed.
Env: 
RN Version: 0.68.5
React Version: 17.0.2
iPhone: 8

**Comment by saurabhg138** [comment] 2023-06-06 13:00
HI any update on this issue?

**Comment by delboy1978uk** [comment] 2023-06-07 09:55
@saurabhg138 the code i mention above, i've been using that successfully since november without issues on both ios and android, give it a try until a fix is out

**Comment by matinzd** [comment] 2023-06-07 10:06
> I confirm this issue exists in iOS 15. I've tested it on iOS 16 and there was no issues. Env: RN Version: 0.68.5 React Version: 17.0.2 iPhone: 8

It's weird. 
Has anyone tested this on a bare project? I am trying to reproduce the issue but no luck.

**Comment by matinzd** [comment] 2023-08-07 10:07
Closing this due to inactivity.

**Closed by matinzd** 2023-08-07 10:07 UTC
Labels: bug
