### ISSUE TITLE
Background color is slightly off when using 6.0.0

### ISSUE THREAD

**Issue by j-piasecki** [lottie-react-native/lottie-react-native#1034] opened 2023-06-12 09:46 UTC
## Description

When using the latest release candidate for version 6.0.0, the background color of the animation is slightly off. In the example below, the background color of the root view is set to the same color as the background of the animation.

When using `5.1.6`:
<img width="549" alt="Screenshot 2023-06-12 at 11 36 19" src="https://github.com/lottie-react-native/lottie-react-native/assets/21055725/af4c56ed-5eb8-4206-b11d-76e50f6b527a">

When using `6.0.0-rc.6`:
<img width="505" alt="Screenshot 2023-06-12 at 11 34 01" src="https://github.com/lottie-react-native/lottie-react-native/assets/21055725/fb925e53-febe-4fd6-8488-509c557c4d40">

## How to reproduce

This is the code used in the screenshots above:
```jsx
import React from 'react';
import {View} from 'react-native';
import Lottie from 'lottie-react-native';
import Animation from './Fireworks.json';

export default function App() {
  return (
    <View style={{flex: 1, backgroundColor: '#061b09'}}>
      <Lottie
        source={Animation}
        autoPlay
        loop
        style={{
          height: 180,
          width: 180,
          marginBottom: 20,
        }}
      />
    </View>
  );
}
```

[And here is the `Fireworks.json` file.](https://github.com/WoLewicki/App/blob/6909f43022df62aa25ddbce146bd9acdad0ea12d/assets/animations/Fireworks.json#L1)

**Comment by matinzd** [comment] 2023-07-24 11:00
I could not reproduce this on rc.8:

https://github.com/lottie-react-native/lottie-react-native/assets/24797481/4f5fb11b-a238-4610-a8b7-893cd4bacf7b

I will close this for now.

**Closed by matinzd** 2023-07-24 11:00 UTC
