### ISSUE TITLE
Could not build Objective-C module 'lottie_react_native'

### ISSUE THREAD

**Issue by ducgiangtrankma** [lottie-react-native/lottie-react-native#1309] opened 2024-12-02 03:47 UTC
### Description

"Could not build Objective-C module 'lottie_react_native'" Xcode 16

I'm using
"lottie-react-native": "^7.1.0",
"react-native": "0.76.0",

### Steps to reproduce

1. yarn add lottie-react-native
2. cd ios, pod install
3. yarn ios

### Snack or a link to a repository

https://github.com/lottie-react-native/lottie-react-native/issues/1117

### Lottie React Native version

7.1.0

### React Native version

0.76.0

### Platforms

iOS

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by matinzd** [comment] 2024-12-02 09:00
Closing this issue due to an invalid reproduction link. To resolve the issue, please try clearing your Xcode cache and running `pod update`.

As shown in the CI build status below, the builds are passing successfully, indicating that the issue may be related to your local setup:

- [iOS Fabric Build Status](https://github.com/lottie-react-native/lottie-react-native/actions/workflows/ios-fabric-build.yml)  
- [iOS Paper Build Status](https://github.com/lottie-react-native/lottie-react-native/actions/workflows/ios-paper-build.yml)

If the issue persists after troubleshooting, feel free to reopen the issue with additional details. Thank you!

**Closed by matinzd** 2024-12-02 09:00 UTC
