### ISSUE TITLE
Extremely slow Android animation

### ISSUE THREAD

**Issue by etodanik** [lottie-react-native/lottie-react-native#1006] opened 2023-04-05 01:49 UTC
### Description

Expo 48 Android animation is MUCH, MUCH slower than iOS (iOS is mega smooth, Android is like, 5-6 FPS)

This is the JSON that I'm using as an animation (it reports a fully compatible matrix on LottieFiles):
[hero.json.zip](https://github.com/lottie-react-native/lottie-react-native/files/11154448/hero.json.zip)

Edit:
The Android device itself is quite capable. It's OnePlus 7 Pro, and runs quite heavy 3D games without any issues. So the GPU should handle this?

**Comment by Immacio** [comment] 2023-06-20 05:24
Any solutions?

**Comment by israelidanny** [comment] 2023-06-20 16:45
@RRaideRR @Immacio , nope. Absolutely no solution. Would be amazing if any contributors or maintainers could give this any attention.

**Comment by israelidanny** [comment] 2023-07-26 16:57
Hi dear maintainers @emilioicai @matinzd @lelandrichardson 
This bug renders this totally unusable for me on Android. I would love to contribute somehow even, but some guidance from maintainers would be super appreciated.

**Comment by matinzd** [comment] 2023-07-26 17:04
Have you tried this animation on a native app as well? Install Lottie Files app and try the animation there and see if that is still slow. 
If it's slow there as well, we cannot do anything on React Native side.

**Comment by punjasin** [comment] 2023-07-27 03:53
i can't fix only way to fix is reduce size in lottie file on after effect or using
optimize lottie from lottie website(need to upload lottie and then use optimize tool) but need to buy yearly subscription

**Comment by TheRogue76** [comment] 2024-01-18 21:40
Hi guys.
We are now supporting dotLottie, a newer more efficient file format for lottie, that is loads the animation directly on the Native side instead of sending it through like we have to do with JSON. Can you guys test that out and see if the problem still exists?

**Comment by TheRogue76** [comment] 2024-02-11 09:34
Closing since there have been no more responses.

**Closed by TheRogue76** 2024-02-11 09:34 UTC

**Comment by devpate9** [comment] 2024-02-12 06:19
@TheRogue76 issue still exists. the small lottie animation itself makes the app slow/lag

**Comment by etodanik** [comment] 2024-02-12 06:21
Yeah, there's nothing about this that's completed. Lottie is practically unusable on Android

**Comment by devpate9** [comment] 2024-02-12 06:22
Yes i see

any solution @etodanik

**Comment by TheRogue76** [comment] 2024-02-12 09:39
Ok. What did you guys try? What were the results? Did you try dotLottie? Loading the animation asset on the native side? I need responses and data otherwise there is very little i can help with

**Comment by TheRogue76** [comment] 2024-02-12 19:41
> @TheRogue76 I have the same issue on Android, how can I use dotlottie with react native? It seems like it works only on native side, isn't it?

In order to work with dotLottie, all you need to do is transform your JSON animation to Lottie using a tool like https://lottiefiles.com/tools/lottie-to-dotlottie or https://iconscout.com/converter/lottie-json-to-dotlottie, and then making one small modification to your metro file: (instructions [here](https://github.com/lottie-react-native/lottie-react-native?tab=readme-ov-file#if-you-want-to-use-lottie-files)). You don't need change any other piece of code on your JS side after that. The import would look the same as it did with JSON (with a different file extension) and everything else would be the same. No need to do anything on the Native side.
If for whatever reason you can not turn your JSON animation into dotLottie and need to squeeze out as much performance as possible, then you can bundle the animation as a native asset, and just pass the name of the asset for the source prop. The component should take care of the rest.

**Comment by RRaideRR** [comment] 2024-02-16 08:46
Unfortunately, I cannot get it working on Android (on iOS dotlottie files work for me). I just created a minimal reproducible example and opened up [an issue](https://github.com/lottie-react-native/lottie-react-native/issues/1182).
