### ISSUE TITLE
CocoaPods crash: CocoaPods could not find compatible versions for pod "lottie-react-native"

### ISSUE THREAD

**Issue by kafauzy** [lottie-react-native/lottie-react-native#806] opened 2021-09-24 05:56 UTC
[!] CocoaPods could not find compatible versions for pod "lottie-react-native":
  In Podfile:
    lottie-react-native (from `../node_modules/lottie-react-native`)

Specs satisfying the `lottie-react-native (from `../node_modules/lottie-react-native`)` dependency were found, but they required a higher minimum deployment target.

"lottie-ios": "^3.2.3",
"lottie-react-native": "^4.1.0",
"react-native": "0.65.1",

**Comment by Saumyadip-Pramanik** [comment] 2021-09-24 06:08
I am also facing this issue. However, as mentioned in the doc, the following is working for me.
    "lottie-ios": "2.5.0",
    "lottie-react-native": "2.6.1",

**Comment by manoj-clix** [comment] 2021-09-24 06:52
Seems like 4.1.0 have issues with lottie-ios": "3.2.3", downgrading "lottie-react-native" to "4.0.3" is working for me.

"lottie-ios": "3.2.3",
"lottie-react-native": "4.0.3",

* use "4.0.3" instead of "^4.0.3"

**Comment by kafauzy** [comment] 2021-09-24 08:32
> Seems like 4.1.0 have issues with lottie-ios": "3.2.3", downgrading "lottie-react-native" to "4.0.3" is working for me.
> 
> "lottie-ios": "3.2.3",
> "lottie-react-native": "4.0.3",
> 
> * use "4.0.3" instead of "^4.0.3"

great! thank you...

**Comment by emilioicai** [comment] 2021-09-24 10:00
This is fixed on the latest version of lottie-react-native (4.1.2), no need to downgrade.

**Closed by emilioicai** 2021-09-24 10:00 UTC

**Comment by louicoder** [comment] 2021-09-25 12:36
> This is fixed on the latest version of lottie-react-native (4.1.2), no need to downgrade.

This worked for me. 🚀
`yarn add lottie-react-native@4.1.2` and `yarn add lottie-ios@3.2.3`

**Comment by ozturkilgim** [comment] 2021-09-27 03:21
Still I'm facing error while pod install.

    "lottie-ios": "^3.2.3",
    "lottie-react-native": "^4.1.3",

**Comment by ozturkilgim** [comment] 2021-09-27 03:26
> > Seems like 4.1.0 have issues with lottie-ios": "3.2.3", downgrading "lottie-react-native" to "4.0.3" is working for me.
> > "lottie-ios": "3.2.3",
> > "lottie-react-native": "4.0.3",
> > 
> > * use "4.0.3" instead of "^4.0.3"
> 
> great! thank you...

Yes, it's working now.

**Comment by emilioicai** [comment] 2021-09-27 07:36
@ozturkilgim did you remove your Pods file and Podfile.lock? It might be the old versions would still be there

**Comment by skkim-pixel-monster** [comment] 2021-09-30 07:01
> @ozturkilgim did you remove your Pods file and Podfile.lock? It might be the old versions would still be there

I also facing error while pod install, Even after deleting all Pods file, node_modules, and Podfile.lock
```
"lottie-ios": "^3.2.3",
"lottie-react-native": "^4.1.3",
```

**Comment by emilioicai** [comment] 2021-09-30 08:07
@skkim-pixel-monster Is it possible you are using RN 64?

**Comment by skkim-pixel-monster** [comment] 2021-09-30 08:16
> @skkim-pixel-monster Is it possible you are using RN 64?

Yes, I'm using  `"react-native": "0.64.1"`

**Comment by billkim84** [comment] 2021-10-01 06:46
I'm having the same issue .

`"lottie-ios": "3.2.3",`
`  "lottie-react-native": "^4.1.3",`
`   "react-native": "0.64.1",`

**Comment by wendysychan** [comment] 2021-10-13 02:43
having the same issue too..

**Comment by incleaf** [comment] 2021-11-01 15:15
This worked for me:

```
"lottie-ios": "3.2.3",
"lottie-react-native": "4.1.2",
```

And 4.1.3 didn't work out for me :sob:

**Comment by BaderSerhan** [comment] 2021-11-04 10:51
So I found a solution that actually worked!

My versions:
```
react-native: 0.61.5
"lottie-ios": "3.2.3",
"lottie-react-native": "4.1.3",
```

1. First, I updated the `platform :ios` version from my Podfile from `10.0` to `11.0`, but that did not work.

2. I tried using `use_frameworks!` in my Podfile, and indeed `pod-install` was successful but I was not able to run the app due to `use_frameworks!` causing an issue with `react-native-screens`, which I must have because I am using `react-navigation`.

3. **Solution:** I installed the following cocoapods plugin (_follow the steps in the README_):
[cocoapods-user-defined-build-types](https://github.com/joncardasis/cocoapods-user-defined-build-types)

And then added the following two lines in my Podfile, and ran `pod-install`:
```
pod 'lottie-ios',  :build_type => :dynamic_framework, :path => '../node_modules/lottie-ios'
pod 'lottie-react-native', :build_type => :dynamic_framework, :path => '../node_modules/lottie-react-native'
```

**NOTE: MAKE SURE YOU ADD `:build_type` field before the `:path`, or else `pod-install` will not work.**

**Comment by Dat-Mobile** [comment] 2022-07-13 17:56
I can confirm that it does work when I change from this
```
"lottie-ios": "^3.2.3",
"lottie-react-native": "^4.1.3",
```
to this
```
"lottie-ios": "3.2.3",
"lottie-react-native": "4.0.3",
```
not really sure the issue is from version or ^
