### ISSUE TITLE
Cannot get any Lottie animations to show in an Expo SDK 48 React Native app.

### ISSUE THREAD

**Issue by hasanjafri** [lottie-react-native/lottie-react-native#999] opened 2023-03-23 14:44 UTC
### Description

Cannot get any Lottie animations to show in an Expo SDK 48 React Native app.

### Steps to Reproduce

1. Install `lottie-react-native` as described by Expo docs [here](https://docs.expo.dev/versions/latest/sdk/lottie/) (we are using the managed workflow)
2. Add LottieView as described within the Expo docs:

`      <LottieView
        autoPlay
        ref={animation}
        style={{
          width: 200,
          height: 200,
          backgroundColor: '#eee',
        }}
        source={require('./assets/gradientBall.json')}
      />`
3. I have tried the various solutions suggested by this [thread](https://github.com/lottie-react-native/lottie-react-native/issues/832) to no luck or avail.

**Expected behavior:** See Lottie Animation on screen. One thing to mention is that we are using [development-client](https://docs.expo.dev/development/create-development-builds/) builds for Expo, so NOT the Expo Go app. We're also using the **hermes** engine if that means anything.

**Actual behavior:** Expect to see Lottie animation on screen but the area is occupied and I can see the background but there is no animation. It never plays and never appears.

### Versions
`  "lottie-react-native": "5.1.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.3",`

**Comment by matinzd** [comment] 2023-03-27 15:28
I am working on releasing v6 and communicating with expo to increase the recommended version and that should fix all the issues for all expo users. 
Stay tuned!

**Comment by hasanjafri** [comment] 2023-03-27 21:59
> I am working on releasing v6 and communicating with expo to increase the recommended version and that should fix all the issues for all expo users. Stay tuned!

Thanks, man! Appreciate your effort!

**Comment by djhogarth** [comment] 2023-03-27 22:23
> I am working on releasing v6 and communicating with expo to increase the recommended version and that should fix all the issues for all expo users. 
> Stay tuned!

When can we expect v6 to be released. Can you give us an estimated time frame?

**Comment by cmosboss** [comment] 2023-04-12 22:15
Same issue also on expo dev client.

**Comment by joelpierre** [comment] 2023-04-13 22:45
V6 works as expected using "next" install. When will it be released officially @matinzd ?

**Comment by matinzd** [comment] 2023-04-14 09:25
> V6 works as expected using "next" install. When will it be released officially @matinzd ?

There are some final touches needs to be done. Maybe in a week. I have been busy for last 3 weeks.

**Comment by joelpierre** [comment] 2023-04-14 21:00
Thanks @matinzd , appreciate the response. I will keep my eyes peeled 👀

**Comment by cbaser** [comment] 2023-05-04 23:07
@matinzd have you update the package? I am still getting the error with expo 48

**Comment by spadeworkstech** [comment] 2023-05-29 04:46
It also crashes in android all the time . but just wondering why its not showing at all . Maybe try wrapping LottieView inside a View and give flex:1 like below 

```
<View style={{ flex: 1 }}>
        <LottieView
          ref={confettiRef}
          source={require("../../assets/lottie/confettiLottie.json")}
          style={{
            width: Dimensions.get("window").width - 100,
            height: Dimensions.get("window").height - 20,
          }}
          autoPlay={false}
          loop={false}
          resizeMode="cover"
        />
      </View>
```

or try using Lottie instead of LottieView (same manner) .

**Comment by matinzd** [comment] 2023-05-29 04:48
> It also crashes in android all the time . but just wondering why its not showing at all . Maybe try wrapping LottieView inside a View and give flex:1 like below
> 
> ```
> <View style={{ flex: 1 }}>
>         <LottieView
>           ref={confettiRef}
>           source={require("../../assets/lottie/confettiLottie.json")}
>           style={{
>             width: Dimensions.get("window").width - 100,
>             height: Dimensions.get("window").height - 20,
>           }}
>           autoPlay={false}
>           loop={false}
>           resizeMode="cover"
>         />
>       </View>
> ```
> 
> or try using Lottie instead of LottieView (same manner) .

Which version are you using? Are you running it with dev client?

**Comment by spadeworkstech** [comment] 2023-05-29 04:52
im using Lottie react native ^5.1.6. Some Json animations are working which has size around <10 kb.

but this confetti animation which has 70kb size fails in android , 

Im using Expo Go .

"expo": "^48.0.9",
"react-native": "0.71.4",
"lottie-react-native": "^5.1.6",

**Comment by matinzd** [comment] 2023-05-29 04:53
> 

Can you try `next` version and let me know if the issue still persists?

**Comment by spadeworkstech** [comment] 2023-05-29 05:23
next version ? I dont get it . I'm using the latest version of lottie .

**Comment by matinzd** [comment] 2023-05-29 05:29
> next version ? I dont get it . I'm using the latest version of lottie .

[6.0.0-rc.6](https://www.npmjs.com/package/lottie-react-native/v/6.0.0-rc.6)

**Comment by JackHull** [comment] 2023-06-04 11:38
This issue still persists for 6.0.0-rc.6 and Expo 48. We cannot get any animations to run at all and have also tried all solutions mentioned by @hasanjafri.

**Comment by hasanjafri** [comment] 2023-07-02 17:03
@matinzd Hey Matin, I know you're a busy guy so no stress but has any progress been made here? Happy to help out to reproduce the exact issue so it's easier to nail down for you guys.

**Comment by matinzd** [comment] 2023-07-03 06:57
> @matinzd Hey Matin, I know you're a busy guy so no stress but has any progress been made here? Happy to help out to reproduce the exact issue so it's easier to nail down for you guys.

I would appreciate it if you can share a reproduction report so that I can test it.

**Comment by RutvikJR** [comment] 2023-07-24 06:01
hi, is there any alternative we can use temporarily, then please mention it here.

**Comment by thecodingrasta** [comment] 2023-08-04 01:09
@hasanjafri @matinzd - Has there been any progress on this bug at all please? I’ve migrated an existing React Native project to Expo and I’m experiencing issues with one of my lottie animations. All lottie animations work on my React Native app, but not Expo.

@spadeworkstech Mentions the size of the json file, I’m able to render an animation 94Kb in size but not another animation 22Kb, so I’m unsure if the size could be an issue, perhaps the format/contents of the json?

Expo v49.0.5
React Native v0.72.3
Lottie-React-Native v5.1.6

**Comment by djhogarth** [comment] 2023-08-04 06:21
I followed this documentation today and got  a total of 4 lottie animations to work in my React Native Expo  project:
https://docs.expo.dev/versions/latest/sdk/lottie/
The only piece code you have to replace is:   const animation = useRef(null); 
Change it to:   const animation = useRef<LottieView>(null) to resolve the errors related to the animation.current?.reset();
and  animation.current?.play() lines of code. 

I will say however that I did have a problem with one lottie animation .json file not working and crashing the app when used. It was downloaded like a month or two ago, and it seems to have disappeared from lottie's catalog of animations. This  animation .json file seems to be an outlier because I tried about 10+ other animations, all of which worked.

Hope this helps and stay blessed!

Expo v49.0.0
React Native v0.72.3
Lottie-React-Native v5.1.6

**Comment by matinzd** [comment] 2023-08-04 09:49
Are you all using expo go or expo with prebuilt and dev client?

**Comment by thecodingrasta** [comment] 2023-08-04 11:14
> Are you all using expo go or expo with prebuilt and dev client?

I'm using Expo Go connected to an AVD, I've also tried on an iOS device and receive the same issue. 
This is the Lottie Animation I'm trying to render and the app crashes with no output to the console - https://lottiefiles.com/animations/red-diamond-Iu5dLF8OZ3
I'm of course following all official documentation available, some animations are working but not this one or another Diamond I've tried. These work fine on my React Native app (without Expo), so I believe the issue is isolated to Expo.

**Comment by thecodingrasta** [comment] 2023-08-04 11:15
@matinzd - I'm using Expo Go connected to an AVD, I've also tried on an iOS device and receive the same issue.
This is the Lottie Animation I'm trying to render and the app crashes with no output to the console - https://lottiefiles.com/animations/red-diamond-Iu5dLF8OZ3
I'm of course following all official documentation available, some animations are working but not this one or another Diamond I've tried. These work fine on my React Native app (without Expo), so I believe the issue is isolated to Expo.

**Comment by matinzd** [comment] 2023-08-04 11:20
Unfortunately, the update is not available on expo go and the latest supported version for expo go is 5.1.6. 
You can either downgrade or use expo install command to install the recommended version. 
If you want to use expo with latest version make sure to use expo prebuilt.

**Comment by matinzd** [comment] 2023-08-04 11:45
/cc @tsapeta

Since you have merged latest version in this PR:

https://github.com/expo/expo/pull/22868

**Comment by JdwApps** [comment] 2023-08-09 17:18
I just tried in my expo project, everything works fine on iOS device, On android device : if i use a file from lottiefiles it works, but if i use a file downloaded from lottielab or lottie editor the app just crash, no error message displayed., i tried adb logcat but im not really used to android code and i couldnt find any readable errors.
lottie 6.1.2, expo 49.0.6, react 18.2.0, react-native : 0.72.3,

**Comment by matinzd** [comment] 2023-08-10 21:10
Lottie is now updated for Expo Go in the next Expo SDK. However, those who are using Expo Prebuilt should not have any problems.
Cheers!

**Closed by matinzd** 2023-08-10 21:10 UTC
Labels: bug

**Comment by RutvikJR** [comment] 2023-08-11 06:05
thanks @matinzd.

**Comment by matheuscostadesign** [comment] 2023-08-14 13:20
> I just tried in my expo project, everything works fine on iOS device, On android device : if i use a file from lottiefiles it works, but if i use a file downloaded from lottielab or lottie editor the app just crash, no error message displayed., i tried adb logcat but im not really used to android code and i couldnt find any readable errors. I did not use expo prebuild since i dont know how to... lottie 6.1.2, expo 49.0.6, react 18.2.0, react-native : 0.72.3,

I have the same problem...

**Comment by matinzd** [comment] 2023-08-14 13:30
> > I just tried in my expo project, everything works fine on iOS device, On android device : if i use a file from lottiefiles it works, but if i use a file downloaded from lottielab or lottie editor the app just crash, no error message displayed., i tried adb logcat but im not really used to android code and i couldnt find any readable errors. I did not use expo prebuild since i dont know how to... lottie 6.1.2, expo 49.0.6, react 18.2.0, react-native : 0.72.3,
> 
> I have the same problem...

We are not able to help without providing any sample repo or error log. Not working can be caused due to different factors and without having a proper reproduction it's not possible to guess. 

Thanks for your understanding.

**Comment by hamdidamar** [comment] 2023-09-29 14:33
Just install lottie again. `npx expo install lottie-react-native`

**Comment by rumfiske** [comment] 2023-12-14 17:46
I can confirm that the new way of downloading lotties will crash android devices in expo go SDK 49. Also only version 5.1,6 of lottie will show animations / play it. With a json from the "old way" of downloading animations.

**Comment by matinzd** [comment] 2023-12-14 17:59
Updated version of lottie for Expo Go will be available in SDK 50.
Since then, there is no way for Expo Go users to prevent this crash. Try downgrading to v5 or use Expo custom dev client or bare RN.

**Comment by matinzd** [comment] 2023-12-14 18:00
> I can confirm that the new way of downloading lotties will crash android devices in expo go SDK 49. Also only version 5.1,6 of lottie will show animations / play it. With a json from the "old way" of downloading animations.

Updated version of lottie for Expo Go will be available in SDK 50.
Since then, there is no way for Expo Go users to prevent this crash. Try downgrading to v5 or use Expo custom dev client or bare RN.
This issue is NOT about Expo Go.

**Comment by OdebisiidowuSolomon** [comment] 2024-01-22 20:07
npx expo install lottie-react-native fixes it, Specifically lottie-react-native@5.1.6 works fine

**Comment by matinzd** [comment] 2024-01-22 20:10
> npx expo install lottie-react-native fixes it, Specifically lottie-react-native@5.1.6 works fine

Try expo 50 and the latest version of lottie and let us know if it is still broken.

**Comment by KKA11010** [comment] 2024-01-24 16:15
> > npx expo install lottie-react-native fixes it, Specifically lottie-react-native@5.1.6 works fine
> 
> Try expo 50 and the latest version of lottie and let us know if it is still broken.

Animation is not rendering.
- expo 50.0.2
- lottie-react-native 6.5.1

Working fine in
- expo 49.0.21
- lottie-react-native 5.1.6

**Comment by matinzd** [comment] 2024-01-26 10:48
> Can confirm that the latest version has same issues, rolled back to 5.1.6 & works fine again.

Have you tried the migration guide for v5 to v6?

**Comment by amitchaudhary140** [comment] 2024-01-28 08:35
For me also it doesn't word after upgrading to Expo SDK 50 with 6.5.1 version.

**Comment by bibhuti9** [comment] 2024-05-13 09:23
I found a solution. Please remove the height and width **point values**.

Before

"h": 121.07,
 "w": 153.26,
After

"h": 121,
"w": 153,
