### ISSUE TITLE
Could not find or use auto-linked library 'swiftWebKit'

### ISSUE THREAD

**Issue by kockok** [lottie-react-native/lottie-react-native#739] opened 2021-03-14 11:23 UTC
### Description

Error raised when building the app.

### Steps to Reproduce

1. run build in the xcode app.
2. error when building

**Expected behavior:** build the app without such error.

**Actual behavior:** 
```
ld: warning: Could not find or use auto-linked library 'swiftWebKit'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native in liblottie-react-native.a(ContainerView.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native in liblottie-react-native.a(AnimationViewManagerModule.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by 4yki** [comment] 2021-03-15 17:55
Exactly the same after upgrading to RN 0.64

**Comment by VicFrolov** [comment] 2021-03-17 07:49
Same issue here on RN 0.64. 

I see this was recently merged (https://github.com/lottie-react-native/lottie-react-native/commit/82a08642e8ab571d7e4643a44273b8149d536e50), but problem persists after pointing package to master, and npm installing / pod install

**Comment by emilioicai** [comment] 2021-03-17 09:28
@VicFrolov This issue is my first prio as it's blocking the release of v4.0.0 but I'm afraid I cannot reproduce the error. Can you make sure you are using the master branch and clean your cache before doing `npm install`? I'm going to need your help to fix this.

**Comment by jctf** [comment] 2021-03-18 11:17
@emilioicai The solution for me was to create an Objective-C bridging header in the iOS project.

**Comment by emilioicai** [comment] 2021-03-18 11:25
@jctf would you mind sending a PR with the file for the bridging header? Thanks!

**Comment by jctf** [comment] 2021-03-18 11:38
@emilioicai it might be easier to describe the steps to take when you upgrade to RN 0.64. 
There are other 3rd parties libs out there that documented exactly these steps. 
A great how-to can be found -> https://teabreak.e-spres-oh.com/swift-in-react-native-the-ultimate-guide-part-1-modules-9bb8d054db03
You would only have to take the steps till the prompted where you choose to configure Objective-C Bridging Header.

Hope that helps.

**Comment by emilioicai** [comment] 2021-03-18 11:42
oh, you mean the bridging header on the main project, not on the lib. Ok, I will update the documentation accordingly. Thanks!

**Closed** 2021-03-18 11:42 UTC

**Comment by kockok** [comment] 2021-03-19 08:43
@emilioicai Simply creating an empty swift file and bridging not working for me...

**Comment by 4yki** [comment] 2021-03-19 14:35
@kockok , make sure to create File.swift + bridging header on the correct level
https://teabreak.e-spres-oh.com/swift-in-react-native-the-ultimate-guide-part-1-modules-9bb8d054db03
**

- In the Group dropdown, make sure to select the group CounterApp, not the project itself.

**

**Comment by Bardiamist** [comment] 2021-05-03 09:46
Also add `"$(SDKROOT)/usr/lib/swift\"` to `LIBRARY_SEARCH_PATHS` can help if you want to remove `File.swift`

**Comment by mrsimply** [comment] 2021-06-16 11:58
> Also add `"$(SDKROOT)/usr/lib/swift\"` to `LIBRARY_SEARCH_PATHS` can help if you want to remove `File.swift`

Works for me, but needed to remove the trailing "\".

**Comment by aescobar-icc** [comment] 2021-06-30 18:45
Just open your project/ios with xcode, then add a new swift file and that's it!! your problem is solved.
at least it worked for me

**Comment by raivieiraadriano92** [comment] 2021-07-01 21:24
> Also add `"$(SDKROOT)/usr/lib/swift\"` to `LIBRARY_SEARCH_PATHS` can help if you want to remove `File.swift`

Thanks @Bardiamist this worked for me

**Comment by chj-damon** [comment] 2021-07-05 05:55
see this: https://developer.apple.com/forums/thread/655438

**Comment by KaueCesar** [comment] 2021-07-06 15:42
Here works to me, open your project/ios with xcode, add a new swift file with bridging-header.

**Comment by ecklf** [comment] 2021-07-09 15:26
Faced the same issue in XCode 13 beta 2 and iOS 15. Can confirm adding a new file with a bridging header works.

**Comment by ibrahimyolbir** [comment] 2021-07-15 14:08
Hello @ecklf  what do you mean by `Can confirm adding a new file with a bridging header works.`. can you explain more. Thanks
by the way i have the following error

```
ld: warning: Could not find or use auto-linked library 'swiftWebKit'
Undefined symbols for architecture x86_64:
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native in liblottie-react-native.a(ContainerView.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native in liblottie-react-native.a(AnimationViewManagerModule.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native in liblottie-react-native.a(hexStringToColor.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftWebKit_$_lottie_react_native)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ibrahimyolbir** [comment] 2021-07-16 09:48
this worked for me 
https://developer.apple.com/forums/thread/655438
```
Figured this out. There is a new library in Xcode 12 that needs to
 be added to the Link Binary with Libraries phase call libSwiftWebKit.tbd. 
Error went away after adding this.

Unfortunately, adding this library breaks compilation with Xcode 11,
 so you'll have to add & remove it depending on which version of Xcode you're using.
```

**Comment by it-crafter** [comment] 2021-07-20 16:07
> Just open your project/ios with xcode, then add a new swift file and that's it!! your problem is solved.
> at least it worked for me

how to do that please  ?

**Comment by aescobar-icc** [comment] 2021-07-20 18:07
> > Just open your project/ios with xcode, then add a new swift file and that's it!! your problem is solved.
> > at least it worked for me
> 
> how to do that please ?
the following is your project structure:

- your-react-native-project
  |- ios
  |- android
  
  the content the ios folder is an xcode project
  
   you must to open this folder with the xcode and then add a new file swift file
   
   
  
![Screen Shot 2021-07-20 at 14 05 50](https://user-images.githubusercontent.com/16610376/126373647-82e4d2e9-1d98-4949-80df-177a7b7b07d6.png)

![Screen Shot 2021-07-20 at 14 06 07](https://user-images.githubusercontent.com/16610376/126373676-8e337329-d5ab-46a9-b22d-c5ebcdc68b7e.png)

**Comment by rush86999** [comment] 2021-08-10 11:30
Bridging header file no longer work any alternative?

**Comment by patlux** [comment] 2022-02-28 09:01
I already had a `File.swift` in my project. I upgraded from 0.66 to 0.67 and got the error mentioned by the thread author.

My solution was to delete the following path from the `LIBRARY_SEARCH_PATHS` setting as you can see with [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.66.1&to=0.67.3):

![CleanShot 2022-02-28 at 09 57 40](https://user-images.githubusercontent.com/4481570/155953940-f63c713f-cd18-4819-bcfd-65de414c6662.png)

Go into Xcode and delete the following line:

![CleanShot 2022-02-28 at 09 57 09](https://user-images.githubusercontent.com/4481570/155954378-97d0a593-2be9-4fe0-a7e1-7b436868e753.png)

**Comment by patlux** [comment] 2022-02-28 09:08
I already had a `File.swift` in my project. I upgraded from 0.66 to 0.67 and got the error mentioned by the thread author.

My solution was to delete the following path from the `LIBRARY_SEARCH_PATHS` setting as you can see with [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.66.1&to=0.67.3):

![CleanShot 2022-02-28 at 09 57 40](https://user-images.githubusercontent.com/4481570/155953940-f63c713f-cd18-4819-bcfd-65de414c6662.png)

Go into Xcode and delete the following line:

![CleanShot 2022-02-28 at 09 57 09](https://user-images.githubusercontent.com/4481570/155954378-97d0a593-2be9-4fe0-a7e1-7b436868e753.png)

**Comment by LoknathPandit** [comment] 2022-10-12 05:47
> > > > Just open your project/ios with xcode, then add a new swift file and that's it!! your problem is solved.
> > > > at least it worked for me
> > > 
> > > 
> > > how to do that please ?
> > 
> > 
> > The following is your project structure:
> > 
> > * your-react-native-project
> >   |- ios
> >   |- android
> >   the content the ios folder is an xcode project
> >   you must to open this folder with the xcode and then add a new file swift file
> > 
> > ![Screen Shot 2021-07-20 at 14 05 50](https://user-images.githubusercontent.com/16610376/126373647-82e4d2e9-1d98-4949-80df-177a7b7b07d6.png)
> > ![Screen Shot 2021-07-20 at 14 06 07](https://user-images.githubusercontent.com/16610376/126373676-8e337329-d5ab-46a9-b22d-c5ebcdc68b7e.png)
> > thanks. it worked for me in react-native 0.64.0 and xcode 12.5

it worked for me.

**Comment by p-schlickmann** [comment] 2023-09-18 15:23
> I already had a `File.swift` in my project. I upgraded from 0.66 to 0.67 and got the error mentioned by the thread author.
> 
> My solution was to delete the following path from the `LIBRARY_SEARCH_PATHS` setting as you can see with [React Native Upgrade Helper](https://react-native-community.github.io/upgrade-helper/?from=0.66.1&to=0.67.3):
> 
> ![CleanShot 2022-02-28 at 09 57 40](https://user-images.githubusercontent.com/4481570/155953940-f63c713f-cd18-4819-bcfd-65de414c6662.png)
> 
> Go into Xcode and delete the following line:
> 
> ![CleanShot 2022-02-28 at 09 57 09](https://user-images.githubusercontent.com/4481570/155954378-97d0a593-2be9-4fe0-a7e1-7b436868e753.png)
> 
> [facebookarchive/react-native-fbsdk#755](https://github.com/facebookarchive/react-native-fbsdk/issues/755)

Oh god, such a legend. Thank you.
