### ISSUE TITLE
Lottie is crashing on Expo Android 

### ISSUE THREAD

**Issue by segun-flexible** [lottie-react-native/lottie-react-native#1118] opened 2023-10-14 06:58 UTC
Am using Expo SDK 49

It always crash my android if I put big Lottie JSON, but it work if I put small Lottie file

It always work on iOS no matter the file, 

Please help us fix this issue

**Comment by matinzd** [comment] 2023-10-22 17:14
Can you try testing the lottie file with Lottie app from Google Play?

**Comment by klassebrasse** [comment] 2023-10-23 07:50
For me, it crashes on android independent of the size of lottie file. Downloaded json from lottiefiles or lottielab throws error.

log: 
FATAL EXCEPTION: main
Process: host.exp.exponent, PID: 26126
java.lang.IllegalStateException: Unable to parse composition
...
Caused by: h6.a: Expected a double but was END_ARRAY at path $.layers[0].shapes[0].it[1].c.k[3]

lottie-react-native: 5.1.6
Expo SDK 49

**Comment by touchesoftware** [comment] 2023-10-27 15:39
Please reinstall package using "npx expo install lottie-react-native" It will solve this issue after install SDK v49.

**Comment by matinzd** [comment] 2023-10-30 14:32
Duplicate of https://github.com/lottie-react-native/lottie-react-native/issues/1124

**Closed by matinzd** 2023-10-30 14:32 UTC

**Comment by antonjoro2008** [comment] 2024-04-19 12:47
> Please reinstall package using "npx expo install lottie-react-native" It will solve this issue after install SDK v49.

Doesn't work. Expo suggests that the correct lottie-react-native version on expo 49.0.15 is 5.1.6 but still crashes with the error ` java.lang.IllegalStateException: Unable to parse composition ........................................................ Caused by: h6.a: Expected a double but was END_ARRAY at path $.layers[1].shapes[0].it[1].c.k[3] `
