### ISSUE TITLE
Build iOS Failed (LottieAnimationView)

### ISSUE THREAD

**Issue by Manh28295** [lottie-react-native/lottie-react-native#1115] opened 2023-10-11 04:22 UTC
### Description

After I update Xcode Version 15.0 (15A240d)
### Image 
![Screenshot 2023-10-11 at 11 12 15](https://github.com/lottie-react-native/lottie-react-native/assets/36253410/f5a3b55b-ba34-4f6c-bea3-738089e47919)

AnimationViewManagerModule.swift
- Only classes that inherit from NSObject can be declared @objc
- Expected type
- Method does not override any method from its superclass
- Cannot convert return expression of type 'ContainerView' to return type 'View?' (aka 'Optional<UIView>')
- Method does not override any method from its superclass
- Type of expression is ambiguous without a type annotation
- Cannot find 'RCT_DEBUG' in scope
- Type of expression is ambiguous without a type annotation
- Cannot find 'RCT_DEBUG' in scope .......

Somebody help me.

### lottie-react-native Version

Version: 5.1.6

**Comment by matinzd** [comment] 2023-10-22 17:17
Can you try v6?

**Comment by arnoldcamas1** [comment] 2023-11-12 11:45
I have xcode Version 15.0.1 (15A507)

Im using the following and does see the same error 

"lottie-ios": "^4.3.3",
"lottie-react-native": "^6.4.0",
"react-native": "0.72.5",

**Comment by matinzd** [comment] 2023-11-24 09:53
Seems like you have a broken installation because the code doesn't look legit from what we have in the release. Closing this for now as it is not reproducible.

**Closed by matinzd** 2023-11-24 09:53 UTC
