### ISSUE TITLE
When using LottieFile, I noticed that my animations appear inconsistent between Android and iOS. It seems like some colors are missing or not displayed correctly.

### ISSUE THREAD

**Issue by chidaihuashi** [lottie-react-native/lottie-react-native#1063] opened 2023-07-25 01:45 UTC
### Description

When using LottieFile, I noticed that my animations appear inconsistent between Android and iOS. It seems like some colors are missing or not displayed correctly.

！！！Since I cannot upload JSON directly, I have placed the contents of the Lottie file in a TXT file.

[AI-3.txt](https://github.com/lottie-react-native/lottie-react-native/files/12156318/AI-3.txt)

### Steps to Reproduce

1.  Load the local file.

**Expected behavior:** 

The display effects on Android and iOS should be consistent. Based on the current situation, the display on Android is missing some elements, while the result on iOS is as expected.

### Versions

{
  myapp: '1.0.9',
  npm: '9.1.1',
  node: '16.16.0',
  v8: '9.4.146.24-node.21',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '1.1.1q+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

**Comment by GabrielvonPlaten** [comment] 2023-09-27 11:08
Same issue here. When testing the app on my Android the animation works as expected, but on my iPhone, it looks like all colors are missing but the outlines of the animation. 

I tested on iOS 17 with iPhone 14, 15, and an emulator of iPhone 13.

"lottie-ios": "^4.3.1",
"lottie-react-native": "^6.3.1",

**Comment by tim-azumuta** [comment] 2024-01-08 19:28
I could reproduce this as well

- lottie-ios 4.3.4
- lottie-react-native 6.5.1

**Comment by dentemm** [comment] 2024-01-08 19:38
I could reproduce this as well

- lottie-ios 4.3.4
- lottie-react-native 6.5.1

Reverting to v5.6.1 solved the problem for me

**Comment by TheRogue76** [comment] 2024-01-18 21:35
Hiya guys.
Thanks for the issue report (And sorry it took so long to get to this part of the list. We had a lot of things to go through) I'll take a look this weekend to see what's up and get back to you. Strange that Switching back to 5.6.1 is fixing it for you. I'll also run it against native Lottie Android and see if it is the same there.
@dentemm @GabrielvonPlaten can I have sample Lottie files from you guys as well?

**Comment by dentemm** [comment] 2024-01-19 09:40
Thanks for looking into this @TheRogue76 ! On Android v6 was working fine in my case, only iOS displayed some areas filled that weren't in design. The attached lottie json is an animated cyclist, and on iOS the wheels are simply a filled circle instead of an animated wheel. 

[loading.json](https://github.com/lottie-react-native/lottie-react-native/files/13987179/loading.json)

**Comment by TheRogue76** [comment] 2024-01-20 10:53
Hi @dentemm.
I ran your animation on the native lottie-ios project with some interesting results. Running it with core animation (or the equivalent of setting the `renderMode` to `HARDWARE` in `lottie-react-native`) results in the glitch you mentioned:
<img width="559" alt="Screenshot 2024-01-20 at 11 28 22" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/562a21d2-358e-4c8e-9555-aba632c703b6">
Rendering on the main thread (the equivalent of setting the `renderMode` to `SOFTWARE` in `lottie-react-native`) however results in the animation showing up correctly:
<img width="559" alt="Screenshot 2024-01-20 at 11 28 53" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/45d18ff2-10ba-4c4a-abd2-32ff059942c8">
The ability to select render mode (basically dumping the rendering of Lottie to the GPU instead of doing it on the CPU, ergo lowering CPU usage) was introduced around the time of V6. That explains why you are experiencing the issue on that version but not the V5.

# Fixes
For now, setting `renderMode` to `SOFTWARE` results in your animation being shown correctly (basically defaulting back to the old behaviour) so you can use V6 again.

<img width="515" alt="Screenshot 2024-01-20 at 11 51 40" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/bae45432-28c1-43e3-ad39-05d0fe730de1">

But this also shows that there is a rendering issue with the Native Lottie iOS package with core animations. I would recommend opening an issue with lottie-ios and providing your animation so that they can fix it on their side.

**Comment by TheRogue76** [comment] 2024-01-20 11:03
As for your original issue @chidaihuashi, You are very much using unsupported Effects:
<img width="1586" alt="Screenshot 2024-01-20 at 12 03 25" src="https://github.com/lottie-react-native/lottie-react-native/assets/40071952/baeaa6c4-912f-433e-a098-7d7315705f2f">

**Comment by dentemm** [comment] 2024-01-20 11:44
Great find, thanks for this @TheRogue76! In that case I'm upgrading to the latest version again.

**Comment by TheRogue76** [comment] 2024-01-20 12:36
Closing this as resolved.

**Closed by TheRogue76** 2024-01-20 12:36 UTC
Labels: wontfix
